export enum typesEnum {
  GETTODOLIST = 'GETTODOLIST',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  REMOVE = 'REMOVE',
  SHOWMODALEDIT = 'SHOWMODALEDIT',
  CLOSEMODALEDIT = 'CLOSEMODALEDIT',
  SHOWMODALCREATE = 'SHOWMODALCREATE',
  CLOSEMODALCREATE = 'CLOSEMODALCREATE',
  TOGGLEDARK = 'TOGGLEDARK',
}

export enum restApiEnum {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}
