export enum typesEnum {
  GETTODOLIST = 'GETTODOLIST',
  CREATE = 'CREATE',
  CREATE_POST = 'CREATE_POST',
  CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS',
  CREATE_POST_ERORR = 'CREATE_POST_ERORR',
  UPDATE = 'UPDATE',
  REMOVE = 'REMOVE',
  SHOWMODALUPDATE = 'SHOWMODALUPDATE',
  CLOSEMODALUPDATE = 'CLOSEMODALUPDATE',
  SHOWMODALCREATE = 'SHOWMODALCREATE',
  CLOSEMODALCREATE = 'CLOSEMODALCREATE',
  TOGGLEDARK = 'TOGGLEDARK',
  CLOSEMODALCREATESAGA = 'CLOSEMODALCREATESAGA',
}

export enum restApiEnum {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}
